### ISSUE TITLE
Shims should terminate the underlying process they are waiting on when they receive a termination signal

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/shimgen#11]
See https://github.com/airportyh/testem/pull/505 for details.

If a shim is waiting for exit on a process and receives a termination signal from elsewhere, they should forward that signal on to the underlying process.

Investigate http://stackoverflow.com/a/22996552/18475 as a possible solution for this.

**Comment by ferventcoder** [comment]
So I can't find a nice way to handle SIGKILL but SIGTERM handling will go into Choco 0.9.9 (will need to regenerate existing shims). It will be out in rc8 (due out this weekend).

**Comment by andyli** [comment]
Somehow it still doesn't work for me.
I opened the shim of the tor.exe from the tor package, sent it SIGTERM. The shim exited but the actual tor.exe remained running... Any idea what's wrong?

**Comment by ferventcoder** [comment]
@andyli Did you reinstall the shim?

**Comment by andyli** [comment]
I tried reinstall, but there is another problem - the version of tor that is provided by the tor package has been removed from its server, thus the package cannot be installed now. I've requested an updated, hope the maintainer will respond soon.
