### ISSUE TITLE
Scrape more information when creating shims

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/shimgen#17]
When inspecting their properties in Explorer, all shimgen files get a `File description` of `ShimGen generated shim`, a `File version` of `0.5.1.0`, a `Product name` of `ShimGen generated shim`, a `Product version` of `0.5.1.4d3409c9`, a `Copyright` of `Copyright c 2012 - Present RealDimensions...`, and a `Language` of `Language Neutral`, regardless of the true values of the executable.

This is incorrect behavior, and it screws with Explorer. It causes false information to be shown in context menus, default programs, and the start menu.

For example, any file extension that is associated with a shim executable with have the description "ShimGen generated shim"; any shim executable capable of opening a file extension will be called "ShimGen generated shim" in the `Open with` context menu; and whenever two shims of the same name are known to Windows, both of them unhelpfully show a version of `0.5.1.0`. This causes chocolatey/choco#374.

 All of these properties should be scraped from the details of the target executable.

**Comment by alexchandel** [comment]
@ferventcoder Any updates on pushing this upstream?

**Comment by ferventcoder** [comment]
Do you consider this a bug or an enhancement?

**Comment by alexchandel** [comment]
@ferventcoder I'm not sure, but I'd have to go with bug, since Explorer context menus for opening file extensions aren't readable with the present shims (there are just a half-dozen "Shimgen-generated shim" entries).

**Comment by ferventcoder** [comment]
Done.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/13028623/cf7b5670-d239-11e5-9bd3-75bc6ab09091.png)

**Comment by alexchandel** [comment]
:+1: awesome!

**Comment by ferventcoder** [comment]
It's also in today's beta.

**Comment by alexchandel** [comment]
How does one install the beta? I'm stuck at 0.9.9.11. Will it make it to the release soon?

**Comment by ferventcoder** [comment]
`choco upgrade chocolatey -pre` - although I'm not sure it quite works just yet.
