### ISSUE TITLE
cmd/gui combination

### ISSUE THREAD

**Issue by Link-Satonaka** [chocolatey/shimgen#18]
The chocolately package uses a shim for mpv and this neatly fails to work in multiple ways.

I'm not familiar with shims and my exposure to them is strictly through mpv not working. I've looked around for something to justify using a shim in general, and so far I've come across this github page that says "because without shims, you'd have to symlink dependencies to bin, too". Why is this a problem? Having an intermediate executable run between the desired software, every single time I run the desired software- I'm questioning the wisdom of going to such lengths to avoid cluttering the chocolatey bin folder. Perhaps someone could shed some light on that? Thank you.

Moving on, the specific bug that plagues mpv- mpv is a gui application, but a log is displayed on the terminal when run from the cmd. The shim does not recognize that mpv is trying to display things in terminal, and so the shim must be bypassed in order to view mpv's terminal output.

**Comment by ferventcoder** [comment]
>  I'm questioning the wisdom of going to such lengths to avoid cluttering the chocolatey bin folder. Perhaps someone could shed some light on that? Thank you.

It's not to avoid clutter, but I can see how you would have gathered that from just a statement of symlinking dependent files. So a short story. I install two different apps that have dependent files that are named the same but they are not compatible with each other, what do you think will happen? The term for this has a long standing history on Windows.

Another issue that is not usually much of a concern is that symlinking is only granted by default to admins on Windows. It would completely render choco useless for those folks that would use it in non-admin scenarios.

**Comment by Link-Satonaka** [comment]
I had thought of that scenario, but didn't think it would be encountered much, given that affected applications likely have their own installers and likely end up in program files, where the problem is neatly avoided.

For applications that don't have a packaged installer and instead rely entirely on chocolatey, hardlinking is available to users. As far as I can tell, a hardlink's only con is that it cannot link somewhere off disk, but I also don't see that as a problem (why would the chocolatey\bin folder be on a different disk than the chocolatey\lib folder?).
For applications that rely entirely on chocolatey and require specific versions of libraries (and, correct me if I'm wrong but we're in extremely-unlikely-to-happen territory now), why not then, and only then, generate a shim?

**Comment by Link-Satonaka** [comment]
To put it more simply, shimgeneration is the default and I think it should be opt-in, where hardlinking is the default.

**Comment by ferventcoder** [comment]
@Link-Satonaka hardlinking suffers the same issues. You still have to hard link the dependent files. And then you run into the possibility of DLL hell.

**Comment by ferventcoder** [comment]
> I had thought of that scenario, but didn't think it would be encountered much, given that affected applications likely have their own installers and likely end up in program files, where the problem is neatly avoided.

Shimming doesn't even occur for any of this.

**Comment by ferventcoder** [comment]
@Link-Satonaka let's move on and talk about the issue at hand. There are plenty of archives available where the shimming has been hashed and rehashed. We would not have created shimgen had it not been necessary, we don't just create things for fun and b/c they are shiny. That would be a waste of time and time isn't something I have in abundance.

> the specific bug that plagues mpv- mpv is a gui application, but a log is displayed on the terminal when run from the cmd. The shim does not recognize that mpv is trying to display things in terminal, and so the shim must be bypassed in order to view mpv's terminal output.

We are looking at adding .shim director files to choco https://github.com/chocolatey/choco/issues/306. This would allow you to state

~~~ini
someexe
- gui
- waitforexit
- usetargetworkingdirectory
~~~ 


Right now if you call `mpv --shimgen-waitforexit` you will get the result you desire.

**Comment by ferventcoder** [comment]
Try `mpv --shimgen-help` to see the options you can pass to the shim.

**Comment by Link-Satonaka** [comment]
I think you did not understand fully. The shim just does not work with mpv- nothing is shown on the terminal (and I believe wait for exit is the mpv package default at the moment). This is an actual bug as far as I can tell, please try it on your PC.

As for shims in general, yes, shims aren't generated for programs with installers, I know. The basis for which you validate using shims is on dependency hell, and I wonder how often this ever actually occurs. Complex, version specific dependencies will have installers. If you manage to find one that doesn't, then use a shim. The alternative you have created is an intermediate step that is unnecessary most of the time, and as shown with mpv, can actually cause problems.

I believe I can create a package that uses the binary.exe.ignore convention, but what you should really do is make it so that a shim is only generated when actually necessary. The package maintainer should opt into creating a shim.

**Comment by ferventcoder** [comment]
>The alternative you have created is an intermediate step that is unnecessary most of the time, and as shown with mpv, can actually cause problems.

As shown with something that has a behavior unlike almost everything else... ;)

**Comment by ferventcoder** [comment]
> I believe I can create a package that uses the binary.exe.ignore convention, but what you should really do is make it so that a shim is only generated when actually necessary. 

One can use Get-BinRoot, put the package on the tools path and then ensure that folder path is added to the PATH environment variable. See the example in `choco new test` (the bottom of the `tools/chocolateyInstall.ps1` file).

This will ensure that mpv doesn't have a shim and the call is actually to the real executable.

> The package maintainer should opt into creating a shim.

Chocolatey is meant to make it less work for maintainers in the biggest set of cases. This is why it's opt out, not opt in.

**Comment by Link-Satonaka** [comment]
>Chocolatey is meant to make it less work for maintainers in the biggest set of cases. This is why it's opt out, not opt in.

The premise of my argument is that hardlinks can be used as a drop in replacement for shims, and the maintainer can specifically use a shim if the package calls for it (which I argue would be a very rare circumstance).

>Get-BinRoot

But isn't that depreciated? Once it is depreciated, how would I proceed?

**Comment by ferventcoder** [comment]
Get-Binroot has a message that it will be deprecated in v1, and will go away in v2. It will be replaced by a more aptly named get-toolsroot (or something else). It's meant to be used for cases like what you are describing or when a tool has plugins that come from other pkgs and they want a central place to be configured.

**Comment by Link-Satonaka** [comment]
I've determined the issue: mpv.exe does not output to the terminal, mpv.com does, and no shim is made for mpv.com by default.

Please review https://github.com/Link-Satonaka/chocopkgs/blob/master/mpv/tools/chocolateyinstall.ps1

And please consider making my approach the default one, where package maintainers are instructed to explicitly create shims, and hardlinks are autogenerated for exe files.

**Comment by ferventcoder** [comment]
https://github.com/Link-Satonaka/chocopkgs/blob/master/mpv/tools/chocolateyinstall.ps1#L11 (use `-Force`) or it will error on upgrades.

Uninstall should unlink the files.

**Comment by ferventcoder** [comment]
> And please consider making my approach the default one, where package maintainers are instructed to explicitly create shims, and hardlinks are autogenerated for exe files.

Will keep it under consideration - there is a possibly another approach altogether that will completely eliminate shims, hardlinks, everything. See https://groups.google.com/forum/#!searchin/chocolatey/app$20paths

**Comment by Link-Satonaka** [comment]
Ah, thank you for the help. I'm still new to chocolatey and don't know the ropes.

I had not heard of app paths, that sounds like an elegant solution! Thank you for taking the time to discuss this issue with me.

If I might bother you for one more thing- "Start-ChocolateyProcessAsAdmin" did not work for me. I run a user account, and the function just ran the process as my user; it did not invoke UAC. Is this a bug, or am I using it wrong?

**Comment by ferventcoder** [comment]
> If I might bother you for one more thing- "Start-ChocolateyProcessAsAdmin" did not work for me. I run a user account, and the function just ran the process as my user; it did not invoke UAC. Is this a bug, or am I using it wrong?

If you are already in an elevated shell, it will not need to prompt.

**Comment by Link-Satonaka** [comment]
I was not in an elevated shell

**Comment by Link-Satonaka** [comment]
Further issues - this happened during a routine install from a non-elevated shell, by a nonadministrative, regular user. 

Downloading hashcheck 64 bit
   from 'https://github.com/gurnec/HashCheck/releases/download/v2.2.3/HashCheckSetup.exe'
 Installing hashcheck...
 Exception calling "Start" with "1" argument(s): "The requested operation requires elevation"
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:76 char:3
 +   $s = [System.Diagnostics.Process]::Start($psi)
 +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     + FullyQualifiedErrorId : Win32Exception
 You cannot call a method on a null-valued expression.
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:81 char:3
 +   $s.StandardError.ReadToEnd() | Out-File $errorFile
 +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     + FullyQualifiedErrorId : InvokeMethodOnNull
 You cannot call a method on a null-valued expression.
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:82 char:3
 +   $s.WaitForExit()
 +   ~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     + FullyQualifiedErrorId : InvokeMethodOnNull
 Get-Content : Cannot find path 'C:\Users\Link\AppData\Local\Temp\chocolatey\-error.stream' because it does not exist.
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:88 char:21
 +       $innerError = Get-Content $errorFile | Out-String
 +                     ~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : ObjectNotFound: (C:\Users\Link\A...y\-error.stream:String) [Get-Content], ItemNotFoundEx 
    ception
     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 [ERROR] Running C:\Users\Link\AppData\Local\Temp\chocolatey\hashcheck\hashcheckInstall.exe with /S  was not
 successful. Exit code was '' Error Message: .
 At C:\ProgramData\chocolatey\helpers\functions\Start-ChocolateyProcessAsAdmin.ps1:92 char:5
 +     throw $errorMessage
 +     ~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: ([ERROR] Running...rror Message: .:String) [], RuntimeException
     + FullyQualifiedErrorId : [ERROR] Running C:\Users\Link\AppData\Local\Temp\chocolatey\hashcheck\hashcheckInstall.e 
    xe with /S  was not successful. Exit code was '' Error Message: .
The install of hashcheck was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\hashcheck\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - hashcheck
