### ISSUE TITLE
shim exe with icon of the exe

### ISSUE THREAD

**Issue by MetaMemoryT** [chocolatey/shimgen#2]
see https://github.com/chocolatey/chocolatey/issues/579

**Comment by ferventcoder** [comment]
This is fixed in shimgen 0.4.0 and will be included in choco 0.9.8.29

**Comment by ferventcoder** [comment]
This works when the path resolves to the exe, but uses the shimgen default. Which unfortunately is what it is doing b/c working path is the same as the current directory.
