### ISSUE TITLE
How does ShimGen work with environment?

### ISSUE THREAD

**Issue by jakepetroules** [chocolatey/shimgen#20]
Does a ShimGen-generated executable forward its environment to the "real" executable when it invokes it? We are having trouble with a tool that executes multiple copies of itself, passing in an environment variable as part of its state. Normally it works fine but running the shimmed version of our tool results in an environment variable not getting sent to the child process.

See [QTCREATORBUG-15494](https://bugreports.qt.io/browse/QTCREATORBUG-15494) for details.

**Comment by ferventcoder** [comment]
It forwards everything on, as in it creates a child process of the real executable that inherits the environment settings from the process the shim is invoked by.

**Comment by ferventcoder** [comment]
I would say check to be sure the shim is starting the right process that would create an environment variable and pass it through. I will also look to see if it is doing something wrong with any process environment variables (I'm not sure it is doing anything out of the ordinary).

**Comment by jakepetroules** [comment]
Was anything like this fixed in shimgen somewhat recently (last couple months or so)? I don't seem to be encountering the problem anymore...

**Comment by ferventcoder** [comment]
@jakepetroules how old was the prior version of Chocolatey that you had installed?

**Comment by ferventcoder** [comment]
And were you using boxstarter?

**Comment by jakepetroules** [comment]
I was using whatever AppVeyor had installed and I don't know what box starter is so I assume not.

**Comment by ferventcoder** [comment]
@jakepetroules We haven't really changed much in shimgen over the last couple of months. I'm going to close this for now as a possible issue related to AppVeyor that appears resolved. If you see this crop up again, please feel free to comment and we can reopen this. Thanks!

**Comment by jakepetroules** [comment]
Will do, thanks.
