### ISSUE TITLE
ShimGen shims swallow references to shimgen?

### ISSUE THREAD

**Issue by malxau** [chocolatey/shimgen#23]
P:\tmp>p:\Choco\tools\shimgen.exe --path="c:\windows\system32\cmd.exe" -c="/c echo" -o "p:\tmp\cmdecho.exe"
...
P:\tmp>cmdecho foo
foo

P:\tmp>cmdecho shimgen
ECHO is on.

P:\tmp>cmdecho shim
shim

P:\tmp>cmdecho ShimGen
ShimGen

P:\tmp>cmdecho abc shimgen xyz
abc xyz

(Found because 'which shimgen' failed erroneously.)

**Comment by ferventcoder** [comment]
Can you provide more information? I'm not sure what is wrong yet without more context.

**Comment by malxau** [comment]
Not sure what information you're asking for.  The above instructions show what's occurring - if I'm trying to execute some random program that is being invoked via a shim that shimgen created, the term "shimgen" will be dropped from any arguments to the child program.  So I can't run "which shimgen" but can run "which ShimGen", etc. The child program will see the first command as equivalent to being invoked without any arguments.

**Comment by ferventcoder** [comment]
Ah, I understand now. Run `cmdecho --shimgen-log --shimgen-help`

Any argument that starts with `shimgen` gets stripped out. We should probably modify this to `shimgen-`.

**Comment by ferventcoder** [comment]
And sorry, sometimes more context about what you are doing helps understand what the issue is.

**Comment by ferventcoder** [comment]
Your response summarized the issue nicely without requiring me to interpret what the example code output provided.

**Comment by malxau** [comment]
Interesting.  I didn't know the shims had such options.  Obviously renaming "shimgen" to "shimgen-" preserves the issue, it just narrows the namespace: with that change "which shimgen" will work but "which shimgen-v3" clearly can't.  (First rule of shimgen: you do not talk about shimgen!  :stuck_out_tongue_winking_eye:)

Thinking more, this also implies that the shims are parsing argument-by-argument which creates its own share of issues.  For example:
```
P:\tmp>echo Hello    World
Hello    World

P:\tmp>cmdecho Hello    World
Hello World
```
The intermediate spaces are lost in the tokenization process.  This even appears to occur when arguments are quoted which seems very scary:
```
P:\tmp>cmdecho "Hello    World"
"Hello World"

P:\tmp>echo foo>"File  with  two  spaces  between  words"

P:\tmp>sdir "File  with  two  spaces  between  words"
\\?\P:\tmp\File with two spaces between words: The system cannot find the file specified.

P:\tmp>p:\Choco\lib\sdir\tools\sdir.exe "File  with  two  spaces  between  words"
────────────────────────────────────────────────────────────
File  with  two  spaces  between  words                  5b
────────────────────────────────────────────────────────────
 1 files, 0 dirs,    5b used, 78.1g vol size, 54.6g vol free
```
Because the spaces are removed prior to the application being invoked, this file is essentially inexpressible to the receiving application via the shim.

**Comment by ferventcoder** [comment]
Not as worried about the spaces - it is curious though. That is something we should also likely handle. Passing all args exactly as passed aside from what gets stripped off.

**Comment by ferventcoder** [comment]
How does that look?

~~~sh
C:\>cmdecho.exe "Hello    World"
"Hello    World"

C:\>cmdecho.exe "Hello    World" --shimgen --shimgen-
"Hello    World" --shimgen

~~~

**Comment by ferventcoder** [comment]
I forgot this one:

~~~sh
C:\>cmdecho.exe "Hello    World" --shimgen --shimgen- shimgen-v3
"Hello    World" --shimgen shimgen-v3
~~~

**Comment by ferventcoder** [comment]
@malxau pushed as https://github.com/ferventcoder/choco/commit/dd115be60dbd6b78690e0f2348a1d0a917e07343 - you can grab the bits and verify from stable branch of choco.

**Comment by malxau** [comment]
Wow, I see you fixed the spacing issues too - very cool!  Thanks for the prompt turnaround!

(One silly question though - it looks like shimgen.exe went from 112k to 843k as part of this change; is that intentional?)

**Comment by ferventcoder** [comment]
It went up that high due to other changes, like #17 and #21.
