### ISSUE TITLE
arguments handling issue

### ISSUE THREAD

**Issue by andyli** [chocolatey/shimgen#27]
If I pass the argument `a[space][space]b` to a shimmed program in the escaped format as follows:
```
myprogram ^"a ^ ^ b^"
```
It will receive `a[space]b`, in which there is only 1 space between a and b.

Without the shim, the program can receive the 2 spaces correctly.

**Comment by ferventcoder** [comment]
I'm not sure, but I believe this was resolved already. Can you take a look at the 0.9.10 beta of Chocolatey and let me know for sure?

**Comment by andyli** [comment]
Indeed! The issue doesn't exist in the shim created by 0.9.10 beta. Hope it will be released soon : )

**Comment by ferventcoder** [comment]
Getting there. There are a few more things we want to finish prior to release.
