### ISSUE TITLE
csc not found

### ISSUE THREAD

**Issue by darryl-davidson** [chocolatey/shimgen#29]
I am attempting to install lessmsi on a windows 2012 Server machine and I am getting an error when creating the shim for lessmsi.

I attached the output I get when attempting to install lessmsi.

Thanks for the help
https://gist.github.com/darryl-davidson/277972188484b6c57a5c5db7d4de00d8

**Comment by ferventcoder** [comment]
First reported at https://groups.google.com/d/msgid/chocolatey/ad3348a3-10cf-4228-bbc8-2342ef29b625%40googlegroups.com.

Thanks @darryl-davidson for reporting this. By chance have you made any changes to the .NET Framework or disabled it in any way?

Shimgen looks for the C# compiler in a couple of folder locations, but it sounds like that folder is likely different on your machine.

What output do you get when you run:

* `dir $env:SystemRoot\Microsoft.Net\Framework`
* `dir $env:SystemRoot\Microsoft.Net\Framework64`

Just for verification sake, does this still error?

`"C:\ProgramData\chocolatey\tools\shimgen.exe" --path="..\\lib\lessmsi\tools\lessmsi-gui.exe" --output="C:\ProgramData\chocolatey\bin\lessmsi-gui.exe"  --iconpath="C:\ProgramData\chocolatey\lib\lessmsi\tools\lessmsi-gui.exe"`

**Comment by darryl-davidson** [comment]
Here are the results of the `dir` commands:
https://gist.github.com/darryl-davidson/ffac2c40ef907de240189ae5a667728c

And the `shimgen.exe` command:
https://gist.github.com/darryl-davidson/e8c5687ed676e2e5f722e69e04f716df

**Comment by ferventcoder** [comment]
What is in the v4.0.30319 folders of both 64 and non-64bit? 

* ` dir $env:SystemRoot\Microsoft.Net\Framework\v4.0.30319 -filter *.exe`
* ` dir $env:SystemRoot\Microsoft.Net\Framework64\v4.0.30319 -filter *.exe`

I'm looking for csc.exe to be here, but I am curious if the other compilers are here.

**Comment by darryl-davidson** [comment]
contents of v4.0.30319 folders:
https://gist.github.com/darryl-davidson/1c50767de375186594cb297fe3268f74

**Comment by ferventcoder** [comment]
Weird that it is not finding it. I wonder if there is possibly something else at play. 

What do you get when you run this in PowerShell?

`Write-Output "$([System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::Windows))"`

**Comment by darryl-davidson** [comment]
https://gist.github.com/darryl-davidson/352bad50a925c51f32176d521ec83f36

**Comment by ferventcoder** [comment]
I wonder then why it fails? csc is clearly where it is looking for it. I may have a version with a better failure message for you to try.

**Comment by darryl-davidson** [comment]
I would love to give it a try.

**Comment by darryl-davidson** [comment]
Any news on a version of shimgen with a better failure message?

**Comment by ferventcoder** [comment]
I actually have had this tab open the whole time. Man time moves quick. That was 20 days ago O_o

**Comment by ferventcoder** [comment]
@darryl-davidson still in progress (apologies on slowness).

**Comment by Arcanum-XIII** [comment]
Hi, got the same issue - too on a Windows Server 2012. If I can help on anything ?

No path were changed — everything is coming with his default, at least for .net and related stuff.

**Comment by ferventcoder** [comment]
@darryl-davidson @Arcanum-XIII [shimgen.zip](https://github.com/chocolatey/shimgen/files/455610/shimgen.zip) Extract shimgen.exe to `c:\ProgramData\chocolatey\tools`. Send over the debug output on that.

**Comment by darryl-davidson** [comment]
That version of shimgen doesn't seem to fail for me: https://gist.github.com/darryl-davidson/d6b27819c7418a484b28cd74e8d52688

**Comment by ferventcoder** [comment]
Perfect - I switched over to finding the Windows directory in a new way.

**Comment by ferventcoder** [comment]
This version will be in 0.10.1, which we hope to release this week sometime.
