### ISSUE TITLE
Mark shimgen-generated executables as compatible with modern Windows versions

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/shimgen#31]
The manifest embedded by shimgen in the generated exes currently contains only the UAC section (requestedExecutionLevel). This causes all those exes to run under Windows Vista compatibility context. This in turn might lead to issues caused by compatibility shims that are present in this context on later Windows versions.

As shimgen-generated code fully supports all released Windows versions, including Windows 10, the manifest embedded in shimgen-generated exes should include the appropriate compatibility declarations, [like the manifest of choco.exe does](https://github.com/chocolatey/choco/blob/6b92c02eb001f10f8bcf3d5ab4fc3165a6d196be/src/chocolatey.console/app.manifest#L26-L35).

**Comment by ferventcoder** [comment]
Great point.

**Comment by ferventcoder** [comment]
This is completed with 0.8.0 and will be in Chocolatey v0.10.6
