### ISSUE TITLE
Prevent execution of command when using --shimgen-noop

### ISSUE THREAD

**Issue by gep13** [chocolatey/shimgen#8]
When you want to find out where a shim is pointed at, you can do:

```choco --shimgen-log```

as an example, which outputs:

![image](https://cloud.githubusercontent.com/assets/1271146/5711319/56b3516e-9aa1-11e4-9a9e-059a357cc3e3.png)

However, as you will see, the call to choco still executes, which is a slight annoyance.  When calling with --shimgen-log, you should be able to prevent the call to the underlying exe.

**Comment by ferventcoder** [comment]
HA! I meant another option like --shimgen-noop

**Comment by gep13** [comment]
That works too :+1:

Sent from my Windows Phone
________________________________

**Comment by ferventcoder** [comment]
Done.
